erda-project/erda-analyzer

Dockerfile
analyzer-alert/pom.xml
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/Main.java
analyzer-alert/src/main/java/schemas/RecordSchema.java
analyzer-alert/src/main/resources/application.properties
analyzer-common/pom.xml
analyzer-common/src/main/java/cloud/erda/analyzer/common/constant/Constants.java
analyzer-error-insight/pom.xml
analyzer-metrics/pom.xml
analyzer-runtime/pom.xml
build.sh
pom.xml

What type of PR is this?
fix
fix the mysql connection timeout
@liuhaoyang

fix mysql connection timeout

---

analyzer-alert/src/main/java/cloud/erda/analyzer/alert/Main.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/sources/AllNotifyTemplates.java

What type of PR is this?
fix
fix the bug of data not insert into cassandra
@liuhaoyang

fix the bug of data not insert into cassandra

---

analyzer-error-insight/src/main/java/cloud/erda/analyzer/errorInsight/functions/ErrorCountMetricMapper.java
analyzer-error-insight/src/main/java/cloud/erda/analyzer/errorInsight/model/ErrorCountState.java

/kind fix
modify the method of get service_id in the ErrorCountState
@liuhaoyang

modify the method of get service_id in the ErrorCountState

---

analyzer-error-insight/src/main/java/cloud/erda/analyzer/errorInsight/functions/ErrorAlertMapper.java
analyzer-error-insight/src/main/java/cloud/erda/analyzer/errorInsight/functions/ErrorCountMetricMapper.java
analyzer-error-insight/src/main/java/cloud/erda/analyzer/errorInsight/model/ErrorInfo.java
analyzer-error-insight/src/main/java/cloud/erda/analyzer/errorInsight/utils/MetricServiceId.java
analyzer-error-insight/src/main/java/cloud/erda/analyzer/errorInsight/utils/MetricServiceIdUtils.java

Add one of the following kinds:
/kind bug
modify error alert serviceid
Which issue(s) this PR fixes:
Fixes #
Specified Reviewers:
/assign @liuhaoyang

modify error alert serviceid

---

analyzer-alert/src/main/java/cloud/erda/analyzer/alert/utils/RepairErrorUrlUtils.java

Add one of the following kinds:
/kind bug
fix the bug of duplicate in the old url
Which issue(s) this PR fixes:
Fixes #
Specified Reviewers:
/assign @liuhaoyang

fix the bug of duplicate in the old url

---

Dockerfile
erda.yml

feature
move tmc functions to erda
Specified Reviewers:
/assign @liuhaoyang

add erda.yml

---

analyzer-alert/src/main/resources/application.properties

feature
modify monitor.addr
Specified Reviewers:
/assign @liuhaoyang

modify monitor.addr

---

analyzer-alert/src/main/java/cloud/erda/analyzer/alert/sources/NotifyTemplateReader.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/utils/RepairErrorUrlUtils.java

Add one of the following kinds:
/kind fix
fix the bug of URL with multiple orgs
@liuhaoyang

fix the bug of URL with multiple orgs

---

erda.yml

update(erda.yml): support cpu bound label

update(erda.yml): support cpu bound label

---

analyzer-alert/src/main/java/cloud/erda/analyzer/alert/functions/AlertEventLevelFilterFunction.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/models/AlertNotifyTarget.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/sources/NotifyReader.java

feature: change alert_notify_target level to string type

bugfix: change alert_notify_target level to string type

---

.github/workflows/git-sync.yml
pipeline.yml

sync to erda cloud to do ci

---

analyzer-alert/src/main/resources/application.properties
analyzer-error-insight/src/main/resources/application.properties

feature: enable es as default storage for error and alert events

feature: enable es as default storage for error and alert events

---

analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/aggregators/DistinctCountFunctionAggregator.java
analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/aggregators/DistinctFunctionAggregator.java
analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/aggregators/FunctionAggregatorDefine.java
analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/aggregators/FunctionAggregatorFactory.java

Add new aggregator `distinct_count` means Calculate the number of deduplication of the field within the window time
usgae
```
"functions":[
{
"aggregator":"distinct_count",
"field":"cluster_name",
"operator":"gte",
"value": 2
}
}
]
```

Add new FunctionAggregator: support distinct_count function

---

analyzer-alert/src/main/java/cloud/erda/analyzer/alert/Main.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/functions/AlertEventMapFunction.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/functions/AlertEventSilenceFunction.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/functions/AlertEventSuppressBroadcastProcessFunction.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/functions/AlertEventTemplateAggregateFunction.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/functions/AlertLevelProcessFunction.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/functions/AlertRecordMapFunction.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/models/AlertEvent.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/models/AlertEventNotifyMetric.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/models/AlertEventNotifyMetricField.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/models/AlertEventSuppress.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/models/AlertRecord.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/models/AlertSuppressType.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/partitioners/AlertRecordKafkaPartitioner.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/sources/AlertEventSuppressReader.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/utils/OutputTagUtils.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/utils/StateDescriptors.java
analyzer-common/src/main/java/cloud/erda/analyzer/common/constant/AlertConstants.java
analyzer-common/src/main/java/cloud/erda/analyzer/common/constant/Constants.java
analyzer-common/src/main/java/cloud/erda/analyzer/common/constant/MetricConstants.java
analyzer-common/src/main/java/cloud/erda/analyzer/common/constant/MetricTagConstants.java
analyzer-common/src/main/java/cloud/erda/analyzer/common/utils/MapUtils.java
analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/functions/MetricAlertSelectFunction.java
analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/functions/MetricGroupTagProcessFunction.java
analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/functions/MetricOperatorProcessFunction.java
analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/functions/MetricSelectProcessFunction.java
analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/models/AggregateResult.java
build.sh

feature:
1. add more infos to analyzer-alert metric.
2. add new metric to statistic the alert-notify processing jobs.
3. add more infos to support the new alert-event.

feature: alert event refactor

---

analyzer-alert/src/main/java/cloud/erda/analyzer/alert/functions/AlertEventMapFunction.java

add alert source to metric tags

fix: add alert source to metric tags

---

erda.yml

ci: switch mysql to rds

---

.github/workflows/git-sync.yml
pipeline.yml

ci: add tag version

---

analyzer-alert/src/main/java/cloud/erda/analyzer/alert/functions/AlertEventMapFunction.java

fix: set alert source error

---

.github/workflows/git-sync.yml

ci: back to no mirror repo

---

analyzer-alert/src/main/java/cloud/erda/analyzer/alert/sources/AlertEventSuppressReader.java

fix: fix suppress expire time error

fix: fix suppress expire time error

---

analyzer-alert/src/main/java/cloud/erda/analyzer/alert/Main.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/functions/AlertEventTargetExcludeFilterFunction.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/functions/AlertLevelProcessFunction.java
analyzer-alert/src/main/java/cloud/erda/analyzer/alert/models/AlertEventNotifyMetricField.java

fix alert reduce && silence count metric error

fix: fix alert reduce && silence count metric error

---

analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/aggregators/FunctionAggregatorDefine.java
analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/aggregators/FunctionAggregatorFactory.java
analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/aggregators/RateFunctionAggregator.java

support function rate with the same semantic in prometheus

support rate like prometheus

---

erda.yml

Update erda.yml,shrink request memory

---

erda.yml

feat: core-service -> erda-server

---

analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/TraceAnalysisFunction.java

add host_ip & service ip for application_service_node metric

add host_ip & service ip for application_service_node metric

---

Dockerfile
build.sh
pipeline.yml

feature: support arm64

---

analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/filters/FilterOperatorDefine.java
analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/filters/FilterOperatorFactory.java
analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/filters/InsensitivelyEqualFilterOperator.java

[Erda link](https://erda.cloud/erda/dop/projects/387/issues/all?id=589326&iterationID=13633&type=BUG)

feat: support ieq operator
